# Generated by Django 3.1.5 on 2021-01-28 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('course', models.ManyToManyField(related_name='mentor_course', to='learning_mgt.Course')),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='profile/picture')),
                ('contact', models.CharField(blank=True, max_length=10)),
                ('alternate_contact', models.CharField(max_length=10)),
                ('relation_with_alternate_contact', models.CharField(max_length=50)),
                ('current_location', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('git_link', models.CharField(max_length=50)),
                ('yr_of_exp', models.FloatField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_score', models.FloatField()),
                ('updated_at', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_mgt.course')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_mgt.mentor')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning_mgt.student')),
            ],
        ),
        migrations.CreateModel(
            name='MentorStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_mgt.course')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_mgt.mentor')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('percentage', models.FloatField(blank=True, default=None)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('till', models.DateField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning_mgt.student')),
            ],
        ),
    ]
