# Generated by Django 3.1.5 on 2021-01-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_mgt', '0002_auto_20210129_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
