# Generated by Django 3.1.5 on 2021-02-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_mgt', '0003_auto_20210130_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorstudent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learning_mgt.student'),
        ),
    ]
