# Generated by Django 3.1.5 on 2021-02-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_mgt', '0004_auto_20210203_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetails',
            name='joined_at',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='till',
            field=models.DateField(default=None),
        ),
    ]
