# Generated by Django 3.1.5 on 2021-02-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_mgt', '0005_auto_20210203_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='current_score',
            field=models.FloatField(blank=True),
        ),
    ]
